FROM qcdis/miniconda3-pdal AS build
COPY retiling-08-04-22-zz-environment.yaml .
RUN conda env update -f retiling-08-04-22-zz-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
COPY --from=build /venv /venv
COPY retiling-08-04-22-zz.py .
RUN ln -s /venv/bin/python /usr/bin/python