FROM qcdis/miniconda3-pdal AS build
COPY geotiff-export-08-04-22-environment.yaml .
RUN conda env update -f geotiff-export-08-04-22-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
COPY --from=build /venv /venv
COPY geotiff-export-08-04-22.py .
RUN ln -s /venv/bin/python /usr/bin/python