FROM qcdis/miniconda3-pdal AS build
COPY generate-word-search-chunks-v1-environment.yaml .
RUN conda env update -f generate-word-search-chunks-v1-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
COPY --from=build /venv /venv
COPY generate-word-search-chunks-v1.py .
RUN ln -s /venv/bin/python /usr/bin/python