FROM continuumio/miniconda3 AS build
COPY vol2bird-main-environment.yaml .
RUN conda env update -f vol2bird-main-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM qcdis/python-vol2bird AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY vol2bird-main.py .

