FROM continuumio/miniconda3 AS build
RUN apt-get update --allow-releaseinfo-change && apt-get -y install gcc g++
COPY fetch-laz-files-(new-system-6)-environment.yaml .
RUN conda env create -f fetch-laz-files-(new-system-6)-environment.yaml
RUN conda install -c conda-forge conda-pack
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
COPY --from=build /venv /venv
COPY fetch-laz-files-(new-system-6).py .
RUN ln -s /venv/bin/python /usr/bin/python