name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - cv2
    - collections
    - torch.nn
    - torch
    - numpy
    - sklearn
    - torchvision.models
    - flwr
    - pandas
