FROM qcdis/miniconda3-pdal AS build
COPY fetch-laz-files-09-05-22-yd-environment.yaml .
RUN conda env update -f fetch-laz-files-09-05-22-yd-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
COPY --from=build /venv /venv
COPY fetch-laz-files-09-05-22-yd.py .
RUN ln -s /venv/bin/python /usr/bin/python